### PR TITLE
Remove unnecessary if

### PR DESCRIPTION
**Pull request by Hardikus**
Replace if with when.

### CODE REVIEW

**Comment by weavejester** [comment]
Why?

**Comment by Hardikus** [comment]
I think 'if' should be idiomatically used when there are two conditions, and 'when' should be used in case of one condition, which is the case here.

**Comment by weavejester** [comment]
I think it's fine. If `if` wasn't idiomatic for one conditions, it wouldn't have that functionality in the first place. `when` is just `if` + `do`, so switching an `if` to a `when` just adds a superfluous `do`.

**Comment by Hardikus** [comment]
Okay, Thanks

**Pull request closed without merging**
