### PR TITLE
Add update-existing-in

### PR DESCRIPTION
**Pull request by eraserhd**
Like update-in, except do not update missing keys.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR. I think we should go with something closer to the definition of `clojure.core/update-in`, so:

```clojure
(defn update-existing-in [m ks f & args]
  (let [up (fn up [m ks f args]
             (let [[k & ks] ks]
               (if-let [kv (find m k)]
                 (if ks
                   (assoc m k (up (val kv) ks f args))
                   (assoc m k (apply f (val kv) args)))
                 m))]
     (up m ks f args))))
```

**Comment by eraserhd** [comment]
@weavejester commit amended and force-pushed.  Your code is unchanged, except for docs and metadata.

I was wondering this while looking at `clojure.core/update-in`'s source, but I guess Clojure is smart enough to not try to not make a thunk when there are no variables closed over, and that's why `f` and `args` are passed to `up`?

**Comment by weavejester** [comment]
There doesn't seem to be much of a measurable difference in performance between passing `f` and `args` as arguments, and passing them via the lexical scope.

I think I like the look of passing them as arguments slightly better, and when in doubt I'm happy to defer to the core implementation, as at least then we can be sure we're not making things any slower.

**Comment by eraserhd** [comment]
So, I think this is ready then?

**Comment by weavejester** [comment]
Yep, looks fine. Thanks for your work on this.

**Pull request merged**
