### PR TITLE
added transducer info to find-first and replace-nth docs

### PR DESCRIPTION
**Pull request by ertugrulcetin**
It's more clear when docs says those fns can be used as transducers.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks. Please make sure your changes and the commit message adhere to the [contributing guidelines](https://github.com/weavejester/medley/blob/master/CONTRIBUTING.md).

**Comment by ertugrulcetin** [comment]
@weavejester changed the commit message 🙂

**Comment by weavejester** [comment]
Thanks, but the commit message is still past tense, not imperative mood, and over 50 characters. Instead, something like this:

    Update find-first and replace-nth docstrings

With regard to the code, please ensure the docstrings wrap at 80 characters.

**Comment by ertugrulcetin** [comment]
@weavejester updated message with that one :) I'll try to follow this pattern, thanks.

**Comment by weavejester** [comment]
I notice you have three identically named commits. Can you squash them down?

**Pull request closed without merging**
