### PR TITLE
Remove the use of 'the' in assoc-some docstring

### PR DESCRIPTION
**Pull request by mbutlerw**
Apologies James, I chose to edit my commit and do a force push to my fork, in an attempt to preserve the original pull request's discussion. It was unaware that this automatically closes the pull request, lesson learnt. 

Hope this isn't an issue, thanks for taking the time to review this.

Link to the original PR: https://github.com/weavejester/medley/pull/48

### CODE REVIEW

**Comment by weavejester** [comment]
> I chose to edit my commit and do a force push to my fork, in an attempt to preserve the original pull request's discussion. It was unaware that this automatically closes the pull request

It shouldn't do... Are you using GitHub's client or something? You can also just reopen the PR, I believe.

The commit looks good, anyway. Can you change the commit message to:

```
Update assoc-some docstring for clarity
```

**Comment by mbutlerw** [comment]
> > I chose to edit my commit and do a force push to my fork, in an attempt to preserve the original pull request's discussion. It was unaware that this automatically closes the pull request
> 
> It shouldn't do... Are you using GitHub's client or something? You can also just reopen the PR, I believe.
> 
> The commit looks good, anyway. Can you change the commit message to:
> 
> ```
> Update assoc-some docstring for clarity
> ```

I think it was because I first pushed the repo with the commit removed, and Github doesn't allow a pull request with no changes.

Updated commit message as per your suggestion.

**Comment by weavejester** [comment]
Thanks, but the commit message body is still there. Can you remove that so it's a one-line commit message?

**Comment by mbutlerw** [comment]
No problem, misunderstood the request, should be a one-line commit message now.

**Pull request merged**
