### PR TITLE
Add function hash-map-by

### PR DESCRIPTION
**Pull request by hlship**
I end up copy-and-pasting this function into a lot of my projects, so this feels like a good home for it.

### CODE REVIEW

**Comment by martinklepsch** [comment]
Would love to see this added as well. 👍

**Comment by borkdude** [comment]
Me too. A better name for it is maybe `index-by` which I've seen in a couple of other places.

**Comment by borkdude** [comment]
Btw, do we still need transients now that we have transducers? 
E.g. `(into {} (map (juxt :a identity)) [{:a 1} {:a 2}])` would maybe have the same performance?

**Comment by fhalde** [comment]
Can index-by be made more generic to accept a collision handling function? This will provide more flexibility in the strategies to be used for handling same keys!

**Comment by weavejester** [comment]
I don't think `index-by` should be made mode complex. Currently there's a nice similarity between `group-by`, which adds values to a vector, and `index-by`, which overwrites values.

If we want a function that handles collisions, I think it should be separate, because its functionality would be a superset of the functionality in `index-by` and `group-by`. I'm also not sure how useful such a function would be.

**Pull request closed without merging**
